name: Multi Jobs Workflow
on:
  push:
    branches:
      - main
jobs:
  first-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: First job step
        run: |
          echo "Hello, First Workflow!"
  second-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: Second job step
        run: |
          echo "Hello, Second Workflow!"